// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
)

type Material struct {
	ID               int64
	Nombre           string
	Descripcion      sql.NullString
	Unidad           string
	PrecioReferencia string
	CreatedAt        string
}
