// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
)

type Equipo struct {
	ID         int64
	Nombre     string
	Tipo       string
	Unidad     string
	CostoHora  string
	Disponible int64
	CreatedAt  string
}

type ManoObra struct {
	ID              int64
	Descripcion     string
	Categoria       string
	Unidad          string
	CostoReferencia string
	CreatedAt       string
}

type Material struct {
	ID               int64
	Nombre           string
	Descripcion      sql.NullString
	Unidad           string
	PrecioReferencia string
	CreatedAt        string
}

type Precio struct {
	ID            int64
	RecursoTipo   string
	RecursoID     int64
	Precio        string
	FechaVigencia string
	CreatedAt     string
}

type Usuario struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    string
}
