// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const actualizarMateriales = `-- name: ActualizarMateriales :one
UPDATE material SET nombre = ?, descripcion = ?, unidad = ?, precio_referencia = ?
WHERE id = ?
RETURNING id, nombre, descripcion, unidad, precio_referencia, created_at
`

type ActualizarMaterialesParams struct {
	Nombre           string
	Descripcion      sql.NullString
	Unidad           string
	PrecioReferencia string
	ID               int64
}

func (q *Queries) ActualizarMateriales(ctx context.Context, arg ActualizarMaterialesParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, actualizarMateriales,
		arg.Nombre,
		arg.Descripcion,
		arg.Unidad,
		arg.PrecioReferencia,
		arg.ID,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Unidad,
		&i.PrecioReferencia,
		&i.CreatedAt,
	)
	return i, err
}

const buscarMaterialPorID = `-- name: BuscarMaterialPorID :one
SELECT id, nombre, descripcion, unidad, precio_referencia, created_at FROM material WHERE id = ?
`

func (q *Queries) BuscarMaterialPorID(ctx context.Context, id int64) (Material, error) {
	row := q.db.QueryRowContext(ctx, buscarMaterialPorID, id)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Unidad,
		&i.PrecioReferencia,
		&i.CreatedAt,
	)
	return i, err
}

const crearMateriales = `-- name: CrearMateriales :one
INSERT INTO material (nombre, descripcion, unidad, precio_referencia, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, nombre, descripcion, unidad, precio_referencia, created_at
`

type CrearMaterialesParams struct {
	Nombre           string
	Descripcion      sql.NullString
	Unidad           string
	PrecioReferencia string
	CreatedAt        string
}

func (q *Queries) CrearMateriales(ctx context.Context, arg CrearMaterialesParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, crearMateriales,
		arg.Nombre,
		arg.Descripcion,
		arg.Unidad,
		arg.PrecioReferencia,
		arg.CreatedAt,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Unidad,
		&i.PrecioReferencia,
		&i.CreatedAt,
	)
	return i, err
}

const eliminarMateriales = `-- name: EliminarMateriales :execrows
DELETE FROM material WHERE id = ?
`

func (q *Queries) EliminarMateriales(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, eliminarMateriales, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listarMateriales = `-- name: ListarMateriales :many
SELECT id, nombre, descripcion, unidad, precio_referencia, created_at FROM material ORDER BY id
`

func (q *Queries) ListarMateriales(ctx context.Context) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, listarMateriales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.Unidad,
			&i.PrecioReferencia,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
